name: Actions for Discord
on: [push, fork, create, delete, deployment, pull_request, release]
# on:
#     - push
#     - fork
#     - create
#     - delete
#     - deployment
#     - pull_request:
#         types: [opened, edited, closed, reopened, release, assigned, ready_for_review, review_requested, review_request_removed]
jobs:
    tell-discord:
        runs-on: ubuntu-latest
        steps:
        -   name: Actions for Discord
            env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            uses: Ilshidur/action-discord@master
